CREATE DATABASE Maybox;

CREATE TABLE client (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nom VARCHAR(155) NOT NULL,
    email VARCHAR(155) NOT NULL UNIQUE,
    mot_de_passe VARCHAR(255) NOT NULL,
    date_inscription TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE equipe (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nom VARCHAR(155) NOT NULL,
    prenom VARCHAR(155) NOT NULL,
    fonction VARCHAR(155) NOT NULL,
    numero_immatriculation VARCHAR(100) NOT NULL,
    telephone VARCHAR(100) NOT NULL,
    email VARCHAR(155) NOT NULL UNIQUE,
    date_inscription TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);